// USERS ACTIONS

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const SELECT_USER = 'SELECT_USER';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const UPDATE_USER = 'UPDATE_USER';

// ALERT ACTIONS

export const SHOW_ADD_ALERT = 'SHOW_ADD_ALERT';
export const SHOW_UPDATE_ALERT = 'SHOW_UPDATE_ALERT';
